// UI
#include "mainwindow.h"
#include "ui_mainwindow.h"
//#include <opencv2/core/core.hpp>
//#include <opencv2/opencv.hpp>
//#include "opencv2/imgcodecs.hpp"
//#include "opencv2/imgproc.hpp"
//#include "opencv2/videoio.hpp"
//#include <opencv2/video.hpp>
//#include <iostream>

// Opencv
#include "opencv2/imgcodecs.hpp"
#include "opencv2/imgproc.hpp"
#include "opencv2/videoio.hpp"
#include <opencv2/highgui.hpp>
#include <opencv2/video.hpp>
#include "opencv2/bgsegm.hpp"
#include <opencv2/opencv.hpp>
#include "opencv2/features2d.hpp"

// SIFT library
#include "opencv2/xfeatures2d.hpp"

//#include <dlib/image_processing.h>
//#include <dlib/data_io.h>
//#include <dlib/image_processing/frontal_face_detector.h>

#include <iostream>
#include <sstream>

#include "backgroundsubtraction.h"

// using namespace dlib;
using namespace std;
using namespace cv;


MainWindow::MainWindow(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui::MainWindow)
{

    ui->setupUi(this);

 //dlib::array<array2d<unsigned char> > images_train, images_test;
//    dlib::frontal_face_detector detector = dlib::get_frontal_face_detector();


      //Variables
    // Creating the pointer Background Subtraction
    BackgroundSubtraction* bs = new BackgroundSubtraction();
    Mat edges;
    Mat fgMask;
    Mat fgMaskMOG; // fg mask generated by MOG method
    Mat fgMaskMOG2; // fg mask generated by MOG2 method
    Mat fgMaskGMG; // fg mask generated by GMG method
    Mat fgMaskKNN; // fg mask generated by KNN method
    Mat resizeF;

    // Create the pointer for SIFT
    cv::Ptr<Feature2D> sift = xfeatures2d::SIFT::create();
    // Create the pointer for SURF
    cv::Ptr<Feature2D> surf = xfeatures2d::SURF::create();
    // Create the pointer for AKAZE
    cv::Ptr<Feature2D> akaze = AKAZE::create();
    // Create the pointer for BoostDesc
    cv::Ptr<Feature2D> boostDesc = xfeatures2d::BoostDesc::create(xfeatures2d::BoostDesc::BINBOOST_256,true,5.00f);
    // Create the pointer for BriefDescriptorExtractor
    cv::Ptr<Feature2D> brief = xfeatures2d::BriefDescriptorExtractor::create();
    // Create the pointer for DAISY
    cv::Ptr<Feature2D> daisy = xfeatures2d::DAISY::create();
    // Create the pointer for LUCID
    cv::Ptr<Feature2D> lucid = xfeatures2d::LUCID::create();
    // Create the pointer for FREAK
    cv::Ptr<Feature2D> freak = xfeatures2d::FREAK::create();
    // Create the pointer for MSDDetector
    cv::Ptr<Feature2D> msd = xfeatures2d::MSDDetector::create();
    // Create the pointer for StarDetector
    cv::Ptr<Feature2D> star = xfeatures2d::StarDetector::create();
    // Create the pointer for VGG
    cv::Ptr<Feature2D> vgg = xfeatures2d::VGG::create(xfeatures2d::VGG::VGG_120,1.4f,true,true,5.0f,false);
    // Create the pointer for AGAST
    cv::Ptr<Feature2D> agast = AgastFeatureDetector::create();
    // Create the pointer for BRISK
    cv::Ptr<Feature2D> brisk = BRISK::create();
    // Create the pointer for GFTTDetector
    cv::Ptr<Feature2D> gftt = GFTTDetector::create();
    // Create the pointer for KAZE
    cv::Ptr<Feature2D> kaze = KAZE::create();
    // Create the pointer for MSER
    cv::Ptr<Feature2D> mser = MSER::create();
    // Create the pointer for FastFeatureDetector
    cv::Ptr<Feature2D> fast = FastFeatureDetector::create();
    // Create the pointer for ORB
    cv::Ptr<Feature2D> orb = ORB::create();
    // Init Key Points
    vector<KeyPoint> keypoints_1;
    // Init descriptors
    Mat descriptors_1;
    Mat img_keypoints_1;
    // Frame gray scale
    Mat grayFrame;
    // Option to save the image
    int optAlgorithm;


      //Messages for the label
      QString infoCamera = "Camera Status";
      QString cameraWorking = "Camera is working";
      QString cameraNotWorking = "Camera is not working";

      //Quit the app
        connect(ui->btQuit, &QPushButton::clicked,this,&QMainWindow::close);


    // Inform about the status of the camera
    ui->lbCameraInfo->setText(infoCamera);



    //Getting frames from the camera
    VideoCapture cap(0); // open the default camera

//        if(!cap.isOpened())  // check if we succeeded
//            ui->lbCameraInfo->setText(cameraNotWorking);
//        else
//        ui->lbCameraInfo->setText(cameraWorking);


        for(;;)
        {
            Mat frame;
            cap >> frame; // get a new frame from camera

            //fgMaskMOG2 = bs -> applyMOG2(frame,fgMaskMOG2);
            //cvtColor(frame, edges, COLOR_BGR2Lab);
            //imshow("Lab Color", edges);

            //imshow("Frame",frame);

            //imshow("FGMask MOG 2",fgMaskMOG2);

            // SIFT section
//            optAlgorithm = 0;
//             First of all it's compulsory to convert the frame to gray scale
//            cvtColor(frame, grayFrame, COLOR_BGR2GRAY);
//            // Detect the keypoints
//            sift->detect(grayFrame, keypoints_1 );
//            // Calculate the descriptors
//            sift->compute(grayFrame, keypoints_1, descriptors_1);
//            // Draw Keypoints
//            drawKeypoints(grayFrame, keypoints_1, img_keypoints_1);
//            // Show detected (drawn) keypoints
//            imshow("Keypoints 1", img_keypoints_1);

            // SURF section
//            optAlgorithm = 1;
//            // First of all it's compulsory to convert the frame to gray scale
//            cvtColor(frame, grayFrame, COLOR_BGR2GRAY);
//            // Detect the keypoints
//            surf->detect(grayFrame, keypoints_1 );
//            // Calculate the descriptors
//            surf->compute(grayFrame, keypoints_1, descriptors_1);
//            // Draw Keypoints
//            drawKeypoints(grayFrame, keypoints_1, img_keypoints_1);
//            // Show detected (drawn) keypoints
//            imshow("Keypoints 1", img_keypoints_1);

            // ORB section
//            optAlgorithm = 2;
//            // First of all it's compulsory to convert the frame to gray scale
//            cvtColor(frame, grayFrame, COLOR_BGR2GRAY);
//            // Detect the keypoints
//            orb->detect(grayFrame, keypoints_1 );
//            // Calculate the descriptors
//            orb->compute(grayFrame, keypoints_1, descriptors_1);
//            // Draw Keypoints
//            drawKeypoints(grayFrame, keypoints_1, img_keypoints_1);
//            // Show detected (drawn) keypoints
//            imshow("Keypoints 1", img_keypoints_1);

            // FAST & BriefDescriptorExtractor section
//            optAlgorithm = 3;
//            // First of all it's compulsory to convert the frame to gray scale
//            cvtColor(frame, grayFrame, COLOR_BGR2GRAY);
//            // Detect the keypoints with FAST
//            fast->detect(grayFrame, keypoints_1 );
//            // Calculate the descriptors with BRIEF
//           brief->compute(grayFrame, keypoints_1, descriptors_1);
//            // Draw Keypoints
//            drawKeypoints(grayFrame, keypoints_1, img_keypoints_1);
//            // Show detected (drawn) keypoints
//           imshow("Keypoints 1", img_keypoints_1);

           // FAST & DAISY section
//           optAlgorithm = 4;
//           // First of all it's compulsory to convert the frame to gray scale
//           cvtColor(frame, grayFrame, COLOR_BGR2GRAY);
//           // Detect the keypoints
//           fast->detect(grayFrame, keypoints_1 );
//           // Calculate the descriptors
//          daisy->compute(grayFrame, keypoints_1, descriptors_1);
//           // Draw Keypoints
//           drawKeypoints(grayFrame, keypoints_1, img_keypoints_1);
//           // Show detected (drawn) keypoints
//          imshow("Keypoints 1", img_keypoints_1);

          // AKAZE & BoostDesc section
//          optAlgorithm = 5;
//          // First of all it's compulsory to convert the frame to gray scale
//          cvtColor(frame, grayFrame, COLOR_BGR2GRAY);
//          // Detect the keypoints
//          akaze->detect(grayFrame, keypoints_1 );
//          // Calculate the descriptors
//         boostDesc->compute(grayFrame, keypoints_1, descriptors_1);
//          // Draw Keypoints
//          drawKeypoints(grayFrame, keypoints_1, img_keypoints_1);
//          // Show detected (drawn) keypoints
//         imshow("Keypoints 1", img_keypoints_1);

            // AKAZE section
//            optAlgorithm = 6;
//            // First of all it's compulsory to convert the frame to gray scale
//            cvtColor(frame, grayFrame, COLOR_BGR2GRAY);
//            // Detect the keypoints
//            akaze->detect(grayFrame, keypoints_1 );
//            // Calculate the descriptors
//            akaze->compute(grayFrame, keypoints_1, descriptors_1);
//            // Draw Keypoints
//            drawKeypoints(grayFrame, keypoints_1, img_keypoints_1);
//            // Show detected (drawn) keypoints
//            imshow("Keypoints 1", img_keypoints_1);

            // FAST & LUCID section
//            optAlgorithm = 7;
//            // Detect the keypoints
//            fast->detect(frame, keypoints_1 );
//            // Calculate the descriptors
//            lucid->compute(frame, keypoints_1, descriptors_1);
//            // Draw Keypoints
//            drawKeypoints(frame, keypoints_1, img_keypoints_1);
//            // Show detected (drawn) keypoints
//            imshow("Keypoints 1", img_keypoints_1);

            // FREAK section
//            optAlgorithm = 8;
//            // First of all it's compulsory to convert the frame to gray scale
//            cvtColor(frame, grayFrame, COLOR_BGR2GRAY);
//            // Detect the keypoints
//            fast->detect(grayFrame, keypoints_1 );
//            // Calculate the descriptors
//            freak->compute(grayFrame, keypoints_1, descriptors_1);
//            // Draw Keypoints
//            drawKeypoints(grayFrame, keypoints_1, img_keypoints_1);
//            // Show detected (drawn) keypoints
//            imshow("Keypoints 1", img_keypoints_1);

            // MSDDetector section
//            optAlgorithm = 9;
//            // First of all it's compulsory to convert the frame to gray scale
//            cvtColor(frame, grayFrame, COLOR_BGR2GRAY);
//            // Detect the keypoints
//            msd->detect(grayFrame, keypoints_1 );
//            // Calculate the descriptors
//            freak->compute(grayFrame, keypoints_1, descriptors_1);
//            // Draw Keypoints
//            drawKeypoints(grayFrame, keypoints_1, img_keypoints_1);
//            // Show detected (drawn) keypoints
//            imshow("Keypoints 1", img_keypoints_1);

            // StarDetector & FREAK
//            optAlgorithm = 10;
//            // First of all it's compulsory to convert the frame to gray scale
//            cvtColor(frame, grayFrame, COLOR_BGR2GRAY);
//            // Detect the keypoints
//            star->detect(grayFrame, keypoints_1 );
//            // Calculate the descriptors
//            freak->compute(grayFrame, keypoints_1, descriptors_1);
//            // Draw Keypoints
//            drawKeypoints(grayFrame, keypoints_1, img_keypoints_1);
//            // Show detected (drawn) keypoints
//            imshow("Keypoints 1", img_keypoints_1);

            // FAST & VGG
//            optAlgorithm = 11;
//            // First of all it's compulsory to convert the frame to gray scale
//            cvtColor(frame, grayFrame, COLOR_BGR2GRAY);
//            // Detect the keypoints
//            fast->detect(grayFrame, keypoints_1 );
//            // Calculate the descriptors
//            vgg->compute(grayFrame, keypoints_1, descriptors_1);
//            // Draw Keypoints
//            drawKeypoints(grayFrame, keypoints_1, img_keypoints_1);
//            // Show detected (drawn) keypoints
//            imshow("Keypoints 1", img_keypoints_1);

            // AKAZE & VGG
//            optAlgorithm = 12;
//            // First of all it's compulsory to convert the frame to gray scale
//            cvtColor(frame, grayFrame, COLOR_BGR2GRAY);
//            // Detect the keypoints
//            akaze->detect(grayFrame, keypoints_1 );
//            // Calculate the descriptors
//            vgg->compute(grayFrame, keypoints_1, descriptors_1);
//            // Draw Keypoints
//            drawKeypoints(grayFrame, keypoints_1, img_keypoints_1);
//            // Show detected (drawn) keypoints
//            imshow("Keypoints 1", img_keypoints_1);

            // SURF & VGG
//            optAlgorithm = 13;
//            // First of all it's compulsory to convert the frame to gray scale
//            cvtColor(frame, grayFrame, COLOR_BGR2GRAY);
//            // Detect the keypoints
//            surf->detect(grayFrame, keypoints_1 );
//            // Calculate the descriptors
//            vgg->compute(grayFrame, keypoints_1, descriptors_1);
//            // Draw Keypoints
//            drawKeypoints(grayFrame, keypoints_1, img_keypoints_1);
//            // Show detected (drawn) keypoints
//            imshow("Keypoints 1", img_keypoints_1);

            // AGAST & SURF
//            optAlgorithm = 14;
//            // First of all it's compulsory to convert the frame to gray scale
//            cvtColor(frame, grayFrame, COLOR_BGR2GRAY);
//            // Detect the keypoints
//            agast->detect(grayFrame, keypoints_1 );
//            // Calculate the descriptors
//            surf->compute(grayFrame, keypoints_1, descriptors_1);
//            // Draw Keypoints
//            drawKeypoints(grayFrame, keypoints_1, img_keypoints_1);
//            // Show detected (drawn) keypoints
//            imshow("Keypoints 1", img_keypoints_1);

            // BRISK
//            optAlgorithm = 15;
//            // First of all it's compulsory to convert the frame to gray scale
//            cvtColor(frame, grayFrame, COLOR_BGR2GRAY);
//            // Detect the keypoints
//            brisk->detect(grayFrame, keypoints_1 );
//            // Calculate the descriptors
//            brisk->compute(grayFrame, keypoints_1, descriptors_1);
//            // Draw Keypoints
//            drawKeypoints(grayFrame, keypoints_1, img_keypoints_1);
//            // Show detected (drawn) keypoints
//            imshow("Keypoints 1", img_keypoints_1);

            // GFTT & FREAK
//            optAlgorithm = 16;
//            // First of all it's compulsory to convert the frame to gray scale
//            cvtColor(frame, grayFrame, COLOR_BGR2GRAY);
//            // Detect the keypoints
//            gftt->detect(grayFrame, keypoints_1 );
//            // Calculate the descriptors
//            freak->compute(grayFrame, keypoints_1, descriptors_1);
//            // Draw Keypoints
//            drawKeypoints(grayFrame, keypoints_1, img_keypoints_1);
//            // Show detected (drawn) keypoints
//            imshow("Keypoints 1", img_keypoints_1);

            // GFTT & SURF
//            optAlgorithm = 17;
//            // First of all it's compulsory to convert the frame to gray scale
//            cvtColor(frame, grayFrame, COLOR_BGR2GRAY);
//            // Detect the keypoints
//            gftt->detect(grayFrame, keypoints_1 );
//            // Calculate the descriptors
//            surf->compute(grayFrame, keypoints_1, descriptors_1);
//            // Draw Keypoints
//            drawKeypoints(grayFrame, keypoints_1, img_keypoints_1);
//            // Show detected (drawn) keypoints
//            imshow("Keypoints 1", img_keypoints_1);

            // KAZE
//            optAlgorithm = 18;
//            // First of all it's compulsory to convert the frame to gray scale
//            cvtColor(frame, grayFrame, COLOR_BGR2GRAY);
//            // Detect the keypoints
//            kaze->detect(grayFrame, keypoints_1 );
//            // Calculate the descriptors
//            kaze->compute(grayFrame, keypoints_1, descriptors_1);
//            // Draw Keypoints
//            drawKeypoints(grayFrame, keypoints_1, img_keypoints_1);
//            // Show detected (drawn) keypoints
//            imshow("Keypoints 1", img_keypoints_1);

            // MSER & SURF
//            optAlgorithm = 19;
//            // First of all it's compulsory to convert the frame to gray scale
//            cvtColor(frame, grayFrame, COLOR_BGR2GRAY);
//            // Detect the keypoints
//            mser->detect(grayFrame, keypoints_1 );
//            // Calculate the descriptors
//            surf->compute(grayFrame, keypoints_1, descriptors_1);
//            // Draw Keypoints
//            drawKeypoints(grayFrame, keypoints_1, img_keypoints_1);
//            // Show detected (drawn) keypoints
//            imshow("Keypoints 1", img_keypoints_1);

            // MSER & FREAK
//            optAlgorithm = 20;
//            // First of all it's compulsory to convert the frame to gray scale
//            cvtColor(frame, grayFrame, COLOR_BGR2GRAY);
//            // Detect the keypoints
//            mser->detect(grayFrame, keypoints_1 );
//            // Calculate the descriptors
//            freak->compute(grayFrame, keypoints_1, descriptors_1);
//            // Draw Keypoints
//            drawKeypoints(grayFrame, keypoints_1, img_keypoints_1);
//            // Show detected (drawn) keypoints
//            imshow("Keypoints 1", img_keypoints_1);




            if(waitKey(10) == 27){
                switch (optAlgorithm) {
                case 0:
                    // SIFT
                    imwrite("../Feature_Descriptors_Algth/SIFT_keypoints.jpg",img_keypoints_1);
                    break;
                case 1:
                    // SURF
                    imwrite("../Feature_Descriptors_Algth/SURF_keypoints.jpg",img_keypoints_1);
                    break;
                case 2:
                    // ORB
                    imwrite("../Feature_Descriptors_Algth/ORB_keypoints.jpg",img_keypoints_1);
                    break;
                case 3:
                    // FAST & BRIEF
                    imwrite("../Feature_Descriptors_Algth/BriefAndFast_keypoints.jpg",img_keypoints_1);
                    break;
                case 4:
                    // FAST & DAISY
                    imwrite("../Feature_Descriptors_Algth/FastAndDaisy_keypoints.jpg",img_keypoints_1);
                    break;
                case 5:
                    // AKAZE & BoostDesc
                    imwrite("../Feature_Descriptors_Algth/AkazeAndBoostDesc_keypoints.jpg",img_keypoints_1);
                    break;
                case 6:
                    // AKAZE
                    imwrite("../Feature_Descriptors_Algth/Akaze_keypoints.jpg",img_keypoints_1);
                    break;
                case 7:
                    // FAST & LUCID
                    imwrite("../Feature_Descriptors_Algth/FastAndLucid_keypoints.jpg",img_keypoints_1);
                    break;
                case 8:
                    // FAST & FREAK
                    imwrite("../Feature_Descriptors_Algth/FastAndFreak_keypoints.jpg",img_keypoints_1);
                    break;
                case 9:
                    // MSDDetector & FREAK
                    imwrite("../Feature_Descriptors_Algth/MSDAndFreak_keypoints.jpg",img_keypoints_1);
                    break;
                case 10:
                    // StarDetector & FREAK
                    imwrite("../Feature_Descriptors_Algth/StarAndFreak_keypoints.jpg",img_keypoints_1);
                    break;
                case 11:
                    // FAST & VGG
                    imwrite("../Feature_Descriptors_Algth/FastAndVGG_keypoints.jpg",img_keypoints_1);
                    break;
                case 12:
                    // AKAZE & VGG
                    imwrite("../Feature_Descriptors_Algth/AkazeAndVGG_keypoints.jpg",img_keypoints_1);
                    break;
                case 13:
                    // SURF & VGG
                    imwrite("../Feature_Descriptors_Algth/SurfAndVGG_keypoints.jpg",img_keypoints_1);
                    break;
                case 14:
                    // AGAST & SURF
                    imwrite("../Feature_Descriptors_Algth/AgastAndSurf_keypoints.jpg",img_keypoints_1);
                    break;
                case 15:
                    // BRISK
                    imwrite("../Feature_Descriptors_Algth/Brisk_keypoints.jpg",img_keypoints_1);
                    break;
                case 16:
                    // GFTT & FREAK
                    imwrite("../Feature_Descriptors_Algth/GFTTAndFreak_keypoints.jpg",img_keypoints_1);
                    break;
                case 17:
                    // GFTT & SURF
                    imwrite("../Feature_Descriptors_Algth/GFTTAndSurf_keypoints.jpg",img_keypoints_1);
                    break;
                case 18:
                    // KAZE
                    imwrite("../Feature_Descriptors_Algth/KAZE_keypoints.jpg",img_keypoints_1);
                    break;
                case 19:
                    // MSER & SURF
                    imwrite("../Feature_Descriptors_Algth/MSERAndSurf_keypoints.jpg",img_keypoints_1);
                    break;
                case 20:
                    // MSER & FREAK
                    imwrite("../Feature_Descriptors_Algth/MSERAndFreak_keypoints.jpg",img_keypoints_1);
                    break;
                default:
                    cout<<"There isn't any algorithm selected"<<endl;
                    break;
                }

                break;
            }

            //if(waitKey(10) == 27) break;
        }



}



MainWindow::~MainWindow()
{
    delete ui;
}
